# AWS CodeDeploy appspec file

version: 0.0
os: linux
files:
  # unzip the build artifact to destination folder
  - source: /
    destination: /home/ec2-user/app/release
permissions:
  # change folder permissions to ec2-user
  - object: /home/ec2-user/app/release
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: ec2-user
